@extends('layout.main')

@section('content')

<div class="container my-5">
    <h1>I miei Film</h1>
    <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Quia consequuntur reprehenderit at amet dolorum ab cumque iure id praesentium esse earum ex numquam voluptatem saepe iste eos, maxime laboriosam hic consequatur asperiores eius quibusdam officia. Modi culpa in architecto sequi ratione ut cum atque voluptates vero debitis ipsa nulla inventore, unde illo quibusdam repudiandae quas repellendus voluptatum quia provident dignissimos maxime quos? Saepe consectetur veritatis quisquam nam eligendi expedita blanditiis culpa ipsum cum rem in dolorum accusantium ea, dolores porro velit odio minima hic tempore maxime architecto aspernatur aliquam nobis. Temporibus eveniet fugiat unde odit dignissimos, quaerat odio sed illum quam, molestiae deleniti alias. Rerum ab, facilis sequi neque doloremque, repellendus blanditiis, excepturi dicta amet a cum. Consequatur delectus autem deserunt eius cupiditate? Veniam unde incidunt at similique nostrum doloremque ea, corrupti maiores vel minus modi molestias voluptas excepturi quasi optio doloribus omnis quaerat iusto perspiciatis blanditiis necessitatibus soluta assumenda repudiandae vero! Reiciendis libero iusto eaque ut eos perspiciatis? Praesentium error dolor, minus dolorum officiis magnam! Fugit quod laborum doloremque impedit pariatur iste distinctio, cupiditate accusantium ab esse minima architecto beatae illum fugiat ducimus numquam explicabo similique quaerat praesentium suscipit quo. Recusandae, nesciunt at ab similique iste unde officiis accusantium atque deleniti explicabo doloremque culpa sapiente dolorem necessitatibus odio nostrum? Eaque eveniet ex, dolores deleniti molestiae veniam illum inventore saepe explicabo ipsum fuga dolore accusamus labore, veritatis reiciendis voluptate corrupti quos commodi animi facere enim velit. Incidunt illum illo quibusdam tempora? Veniam dolorem iusto ipsa quidem, doloremque deleniti officia nemo quasi. Eum, earum amet! Impedit, earum vel ea, officia eum suscipit repudiandae exercitationem saepe sed provident rem quis expedita delectus id eveniet temporibus! Reiciendis, praesentium! Impedit nisi incidunt iusto pariatur consectetur obcaecati. Fugit assumenda ut eligendi cum maxime minus, sequi voluptatem. Eum eos id sapiente quibusdam, ut perspiciatis quod delectus?</p>
</div>

@endsection
